---
- hosts: all
  vars:
    eap_archive_name: jboss-eap-7.1.0-maven-repository.zip
    dm_archive_name: rhdm-7.0.1-maven-repository.zip
    mvn_repo_dir: ~/mvn_repo
  tasks: 
  - name: EAP 7.1.0 のmaven repositoryのアーカイブを配布する
    copy: 
        src: /home/awx/mvn_repo/{{eap_archive_name}}
        dest: ~/tmp/{{eap_archive_name}}
  - name: ファイルの所有者を変更
    file:
        path: ~/tmp/{{eap_archive_name}}
        owner: daijik
        group: daijik
        mode: "u=rw,g=r,o=r"
  - name: Mavenリポジトリ用のディレクトリを作成
    file:
        path: {{mvn_repo_dir}}
        state: directory
  - name: EAPのMavenリポジトリのアーカイブを展開
    unarchive:
        src: ~/tmp/{{eap_archive_name}}
        dest: ~/mvn_repo
        remote_src: yes

  - name: RHDM 7.0.1 のmaven repositoryのアーカイブを配布する
    copy: 
        src: /home/awx/mvn_repo/{{dm_archive_name}}
        dest: ~/tmp/{{dm_archive_name}}
  - name: ファイルの所有者を変更
    file:
        path: ~/tmp/{{dm_archive_name}}
        owner: daijik
        group: daijik
        mode: "u=rw,g=r,o=r"
  - name: Mavenリポジトリ用のディレクトリを作成
    file:
        path: {{mvn_repo_dir}}
        state: directory
  - name: DMのMavenリポジトリのアーカイブを展開
    unarchive:
        src: ~/tmp/{{dm_archive_name}}
        dest: ~/mvn_repo
        remote_src: yes
