---
- name: Git UNinstalled
  hosts: web
  become: yes
  tasks:
  - name: latest Git version UNinstalled
    yum:
      name: git
      state: absent
  - name: latest Git version UNinstalled
    yum:
      name: git-core
      state: absent
  - name: latest Git version UNinstalled
    yum:
      name: git-core-doc
      state: absent
