---
- hosts: all
  tasks: 
  - name: tunedパッケージを最新版にする
    yum: name=tuned state=latest
  - name: util-linuxパッケージを最新版にする
    yum: name=util-linux state=latest
  - name: samba-clientパッケージを最新版にする
    yum: name=samba-client state=latest
  - name: gitパッケージを最新版にする
    yum: name=git state=latest
  - name: libvirt-daemon-kvm パッケージを最新版にする (added 2018/08/27)
    yum: name=libvirt-daemon-kvm state=latest
  - name: glusterfs パッケージを最新版にする (added 2018/08/27)
    yum: name=glusterfs state=latest
  - name: dracut パッケージを最新版にする (added 2018/08/27)
    yum: name=dracut state=latest
  - name: libmspack パッケージを最新版にする (added 2018/08/27)
    yum: name=libmspack state=latest
  - name: tree パッケージを最新版にする (added 2018/08/28)
    yum: name=tree state=latest
